### ISSUE TITLE
Capstan build hangs

### ISSUE THREAD

**Issue by rowlandwatkins** [cloudius-systems/capstan#135]
Hi folks,

OK, so I've had great success using capstan on my local dev VM (ubuntu under VM Workstation), using KVM as the execution environment.

Now I'd like to replicate this onto a fresh Ubuntu server running Jenkins, so I can create a build pipeline for OSv images, that can target various environments (ESX, EC2, etc.). Capstan should be perfect and not require the entire OSv+apps source tree, just a stock image.

However, I seem to have hit a hurdle - when running capstan build on my job (scala+akka) the underlying build will succeed, but after transferring the payload via CPIO, capstan (or something) hangs:

[[[
$ capstan build
Building blah...
Uploading files...
1 / 1 [==================================================================] 100.00 %
]]]

I'm guessing this might actually be a KVM networking issue, but it's not clear. Are there any logs to activate on capstan that can give me some hints on what to do next?

In the meantime I can build the entire image from scratch just with the source tree and the ESX instructions for now, it's just a little more time consuming.

Any tips would be most appreciated!

Cheers,

Rowland

**Comment by dorlaor** [comment]
On Tue, Jan 6, 2015 at 10:58 AM, Rowland Watkins <notifications@github.com>
wrote:

> Hi folks,
>
> OK, so I've had great success using capstan on my local dev VM (ubuntu
> under VM Workstation), using KVM as the execution environment.
>
> Now I'd like to replicate this onto a fresh Ubuntu server running Jenkins,
> so I can create a build pipeline for OSv images, that can target various
> environments (ESX, EC2, etc.). Capstan should be perfect and not require
> the entire OSv+apps source tree, just a stock image.
>
> However, I seem to have hit a hurdle - when running capstan build on my
> job (scala+akka) the underlying build will succeed, but after transferring
> the payload via CPIO, capstan (or something) hangs:
>
> [[[
> $ capstan build
> Building blah...
> Uploading files...
> 1 / 1 [==================================================================]
> 100.00 %
> ]]]
>

Hi Rowland,

Can you try running with verbose on (-v) ?
It seems indeed it's a network issue, when you use the capstan-example
project you should see the following:

capstan build -v
Building capstan-example...
OSv v0.16
eth0: 192.168.122.15
Waiting for connection from host...
Uploading files...
hello.so  --> /tools/hello.so
Adding /tools/hello.so...

**Comment by rowlandwatkins** [comment]
Hi Dor,

Ah, ok, added -v and I have some interesting output:

[[[
Building blah...
OSv v0.16-31-g927ea7e
eth0: 192.168.122.15
Waiting for connection from host...
Uploading files...
Adding /blah.jar...
target/scala-2.11/blah-assembly-1.3.jar  --> /blah.jar
Aborted

[backtrace]
0x0000000000445371 <osv::generate_signal(siginfo&, exception_frame*)+49>
0x00000000004453da <osv::handle_mmap_fault(unsigned long, int, exception_frame*)+26>
0x000000000032ef43 <mmu::vm_fault(unsigned long, exception_frame*)+147>
0x0000000000392379 <page_fault+105>
0x0000000000391266 <???+3740262>
0x0000000000413a49 <boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex>::~connection_body()+153>
0x000000000021678d <boost::detail::sp_counted_base::release()+45>
0x0000000000414513 <std::_List_base<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> >, std::allocator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> > > >::_M_clear()+51>
0x00000000004145e6 <boost::detail::sp_counted_impl_p<boost::signals2::detail::grouped_list<int, std::less<int>, boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> > > >::dispose()+38>
0x000000000021678d <boost::detail::sp_counted_base::release()+45>
0x000000000041367d <boost::detail::sp_counted_impl_p<boost::signals2::detail::signal_impl<void (), boost::signals2::optional_last_value<void>, int, std::less<int>, boost::function<void ()>, boost::function<void (boost::signals2::connection const&)>, boost::signals2::mutex>::invocation_state>::dispose()+45>
0x000000000021678d <boost::detail::sp_counted_base::release()+45>
0x0000000000413628 <boost::detail::sp_counted_impl_p<boost::signals2::detail::signal_impl<void (), boost::signals2::optional_last_value<void>, int, std::less<int>, boost::function<void ()>, boost::function<void (boost::signals2::connection const&)>, boost::signals2::mutex> >::dispose()+40>
0x000000000021678d <boost::detail::sp_counted_base::release()+45>
0x00000000004119f0 <osv::application::~application()+128>
0x00000000002173b3 <std::vector<std::shared_ptr<osv::application>, std::allocator<std::shared_ptr<osv::application> > >::~vector()+131>
0x0000000000212ab3 <do_main_thread(void*)+1651>
0x0000000000440895 <???+4458645>
0x00000000003eda07 <thread_main_c+39>
0x00000000003921e5 <???+3744229>
]]]

Looks like something is barfing, which is causing the hang - is there any other information I can provide you?

Cheers,

Rowland

**Comment by nyh** [comment]
Pawel, perhaps this is related to commit
28bef7c6a44d8061cb7a4b408c8121d5d6b982fe?

I wonder if this can be reproduced without Capstan (so far I couldn't).

On Tue, Jan 6, 2015 at 11:47 AM, Rowland Watkins <notifications@github.com>
wrote:

> Hi Dor,
>
> Ah, ok, added -v and I have some interesting output:
>
> [[[
> Building blah...
> OSv v0.16-31-g927ea7e
> eth0: 192.168.122.15
> Waiting for connection from host...
> Uploading files...
> Adding /blah.jar...
> target/scala-2.11/blah-assembly-1.3.jar --> /blah.jar
> Aborted
>

Is this /blah.jar the only file that was supposed to be uploaded (in other
words., the upload fully succeeded, and OSv is crashing while shutting
down)?

> [backtrace]
> 0x0000000000445371
> 0x00000000004453da
> 0x000000000032ef43
> 0x0000000000392379
> 0x0000000000391266 <???+3740262>
> 0x0000000000413a49 >, boost::signals2::slot >,
> boost::signals2::mutex>::~connection_body()+153>
> 0x000000000021678d boost::detail::sp_counted_base::release()+45
> 0x0000000000414513 >, boost::signals2::slot >, boost::signals2::mutex> >,
> std::allocator >, boost::signals2::slot >, boost::signals2::mutex> > >
> >::_M_clear()+51>
> 0x00000000004145e6 , boost::shared_ptr >, boost::signals2::slot >,
> boost::signals2::mutex> > > >::dispose()+38>
> 0x000000000021678d boost::detail::sp_counted_base::release()+45
> 0x000000000041367d , int, std::less, boost::function, boost::function,
> boost::signals2::mutex>::invocation_state>::dispose()+45>
> 0x000000000021678d boost::detail::sp_counted_base::release()+45
> 0x0000000000413628 , int, std::less, boost::function, boost::function,
> boost::signals2::mutex> >::dispose()+40>
> 0x000000000021678d boost::detail::sp_counted_base::release()+45
> 0x00000000004119f0 osv::application::~application()+128
> 0x00000000002173b3 std::vector<std::shared_ptr<osv::application,
> std::allocatorstd::shared_ptr<osv::application > >::~vector()+131>
> 0x0000000000212ab3
> 0x0000000000440895 <???+4458645>
> 0x00000000003eda07
> 0x00000000003921e5 <???+3744229>
> ]]]
>
> Looks like something is barfing, which is causing the hang - is there any
> other information I can provide you?
>
Cheers,
>
> Rowland
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cloudius-systems/capstan/issues/135#issuecomment-68845482>
> .
>



-- 
Nadav Har'El
nyh@cloudius-systems.com

**Comment by dorlaor** [comment]
Another thing to try is just to build the capstan-example project and see
if it works.
Your base image is one that you created or a temporary one, can you erase it
by capstan rmi cloudius/osv-base and re-build your capstan image so it will
fetch a new base from s3 ?

You're welcome to share the capstanfile+jar so we can test it locally.

**Comment by rowlandwatkins** [comment]
Interesting, the capstan-java-example exits cleanly.

OK, this looks like a custom image creation problem:

1) make image=openjdk8,httpserver
2) capstan import build/release.x64/usr.img
3) capstan build
4) boom!

So the base for my Capstanfile was a openjdk8+httpserver custom image installed into my local capstan repo. Replacing it with a stock openjdk7/8 exited cleanly on build.

I can confirm now that capstan build will work properly for cloudius/osv-openjdk and cloudius/osv-openjdk8. I only rolled my own for the httpserver, but I'm not sure that these images include that, is that correct?

Cheers,

Rowland

**Comment by dorlaor** [comment]
On Tue, Jan 6, 2015 at 12:34 PM, Rowland Watkins <notifications@github.com>
wrote:

> Interesting, the capstan-java-example exits cleanly.
>
> OK, this looks like a custom image creation problem:
>
> 1) make image=openjdk8,httpserver
> 2) capstan import build/release.x64/usr.img
> 3) capstan build
> 4) boom!
>
> So the base for my Capstanfile was a openjdk8+httpserver custom image
> installed into my local capstan repo. Replacing it with a stock openjdk7/8
> exited cleanly on build.
>
> I can confirm now that capstan build will work properly for
> cloudius/osv-openjdk and cloudius/osv-openjdk8. I only rolled my own for
> the httpserver, but I'm not sure that these images include that, is that
> correct?
>
All images include the httpserver as it is the base for the restapi which
is the single path
for system mgmt w/ OSv  (the CLI and GUI are built over it).
I don't know why there is an issue w/ building your own, I'm trying it now
(java build takes long time)

**Comment by rowlandwatkins** [comment]
I recall having a few issues with building openjdk8:

1) Configure: it resolutely refused to find freetype2
2) CPIO copy: it wanted scala libs of a certain naming convention (current scala libs in /usr/share/scala/lib include the version numbers)

I think the reason for the scala libs being included is a side-effect of using the scala-example which includes a usr.manifest with dependencies, it's possible I built the whole custom image with that to begin with and it kept them in there after. That's all I can think of at present.

Would it help to provide you with my custom image? It's around 300MB.

Cheers,

Rowland

**Comment by dorlaor** [comment]
On Tue, Jan 6, 2015 at 2:16 PM, Rowland Watkins <notifications@github.com>
wrote:

> I recall having a few issues with building openjdk8:
>
> 1) Configure: it resolutely refused to find freetype2
> 2) CPIO copy: it wanted scala libs of a certain naming convention (current
> scala libs in /usr/share/scala/lib include the version numbers)
>
> I think the reason for the scala libs being included is a side-effect of
> using the scala-example which includes a usr.manifest with dependencies,
> it's possible I built the whole custom image with that to begin with and it
> kept them in there after. That's all I can think of at present.
>
> Would it help to provide you with my custom image? It's around 300MB.
>

I tried to build jvm8 and had trouble w/ Fedora. Tomek/Pekka, can you
please continue from here?

**Comment by rowlandwatkins** [comment]
Would it make sense to try the Azul Systems Zulu OpenJDK? It's a verified TCK build I believe, and probably won't be such a moving target compared to the main OpenJDK repo...

**Comment by dorlaor** [comment]
On Tue, Jan 6, 2015 at 4:18 PM, Rowland Watkins <notifications@github.com>
wrote:

> Would it make sense to try the Azul Systems Zulu OpenJDK? It's a verified
> TCK build I believe, and probably won't be such a moving target compared to
> the main OpenJDK repo...
>
>
You can give it a shot. Oracle's jdk does work. In the past they used a
Linux kernel
model, but maybe they stopped or it's not on every Azul jdk.

**Comment by dorlaor** [comment]
On Tue, Jan 6, 2015 at 2:32 PM, Dor Laor <dor@cloudius-systems.com> wrote:

>
>
> On Tue, Jan 6, 2015 at 2:16 PM, Rowland Watkins <notifications@github.com>
> wrote:
>
>> I recall having a few issues with building openjdk8:
>>
>> 1) Configure: it resolutely refused to find freetype2
>> 2) CPIO copy: it wanted scala libs of a certain naming convention
>> (current scala libs in /usr/share/scala/lib include the version numbers)
>>
>> I think the reason for the scala libs being included is a side-effect of
>> using the scala-example which includes a usr.manifest with dependencies,
>> it's possible I built the whole custom image with that to begin with and it
>> kept them in there after. That's all I can think of at present.
>>
>> Would it help to provide you with my custom image? It's around 300MB.
>>
>
> I tried to build jvm8 and had trouble w/ Fedora. Tomek/Pekka, can you
> please continue from here?
>

Which modules did you use exactly? We have openjdk8 and openjdk8-fedora
modules. We use the latter to build the osv-openjdk8 image, the former may
be out of date now. So if you can, please use openjdk8-fedora.

**Comment by tgrabiec** [comment]
The above comment ("Which modules...") was mine, looks like a github bug related to reply via email.

**Comment by rowlandwatkins** [comment]
Ah, I originally used the openjdk8 module, not openjdk8-fedora - I'll have a go tomorrow with the fedora flavour and give feedback, I'd like to try mixing in the TLS functionality too.

Would it make sense to prune the app repo to remove the defunct openjdk8?

**Comment by nyh** [comment]
On Tue, Jan 6, 2015 at 11:59 AM, Nadav Har'El <nyh@cloudius-systems.com>
wrote:

> Pawel, perhaps this is related to commit
> 28bef7c6a44d8061cb7a4b408c8121d5d6b982fe?
>
> I wonder if this can be reproduced without Capstan (so far I couldn't).
>

I found an easy way to reproduce this problem:

    make image=java
    scripts/run.py -e 'java.so -version'

This is supposed to show Java's version and exit, but it never exits, and
apparently uses some CPU (13%), I have no idea for what.

I'll open an issue and debug this.

**Comment by nyh** [comment]
On Wed, Jan 7, 2015 at 4:21 PM, Rowland Watkins <notifications@github.com>
wrote:

> Ah, I originally used the openjdk8 module, not openjdk8-fedora - I'll have
> a go tomorrow with the fedora flavour and give feedback, I'd like to try
> mixing in the TLS functionality too.
>
> Would it make sense to prune the app repo to remove the defunct openjdk8?
>
>
I tried to compile now the "openjdk8" module (make image=openjdk8) and
failed on some bizarre compilation error deep inside openjdk's makefiles:

gmake[8]: Entering directory
'/home/nyh/osv/apps/openjdk8/upstream/jdk8/build/linux-x86_64-normal-server-release/hotspot/linux_amd64_compiler2/product'
/usr/bin/gmake: invalid option -- '8'
/usr/bin/gmake: invalid option -- '/'
/usr/bin/gmake: invalid option -- 'a'
/usr/bin/gmake: invalid option -- '/'
/usr/bin/gmake: invalid option -- 'c'

I really have no interest in debugging this huge openjdk makefiles, since
it's easy to get the openjdk binaries (like we did in the openjdk8-fedora
module),

Gleb, what do you say - shall I remove the "openjdk8" module? Is there a
reason why it is useful to keep it around?


-- 
Nadav Har'El
nyh@cloudius-systems.com

**Comment by nyh** [comment]
On Thu, Jan 08, 2015 at 01:47:40PM +0200, Nadav Har'El wrote:
> On Wed, Jan 7, 2015 at 4:21 PM, Rowland Watkins <notifications@github.com>
> wrote:
> 
> > Ah, I originally used the openjdk8 module, not openjdk8-fedora - I'll have
> > a go tomorrow with the fedora flavour and give feedback, I'd like to try
> > mixing in the TLS functionality too.
> >
> > Would it make sense to prune the app repo to remove the defunct openjdk8?
> >
> >
> I tried to compile now the "openjdk8" module (make image=openjdk8) and
> failed on some bizarre compilation error deep inside openjdk's makefiles:
> 
> gmake[8]: Entering directory
> '/home/nyh/osv/apps/openjdk8/upstream/jdk8/build/linux-x86_64-normal-server-release/hotspot/linux_amd64_compiler2/product'
> /usr/bin/gmake: invalid option -- '8'
> /usr/bin/gmake: invalid option -- '/'
> /usr/bin/gmake: invalid option -- 'a'
> /usr/bin/gmake: invalid option -- '/'
> /usr/bin/gmake: invalid option -- 'c'
> 
> I really have no interest in debugging this huge openjdk makefiles, since
> it's easy to get the openjdk binaries (like we did in the openjdk8-fedora
> module),
> 
> Gleb, what do you say - shall I remove the "openjdk8" module? Is there a
> reason why it is useful to keep it around?
> 
Not that I can think of.

--
			Gleb.

**Comment by nyh** [comment]
On Tue, Jan 6, 2015 at 11:59 AM, Nadav Har'El <nyh@cloudius-systems.com>
wrote:

> Pawel, perhaps this is related to commit
> 28bef7c6a44d8061cb7a4b408c8121d5d6b982fe?
>
> I wonder if this can be reproduced without Capstan (so far I couldn't).
>

I confirmed that indeed this exact commit causes a similar bug in java.so
not exiting (see https://github.com/cloudius-systems/osv/issues/572). It
might not be the same underlying cause (I still don't know if it's a bug in
our code or detached threads really staying behind), but it looks awfully
similar.

**Comment by nyh** [comment]
2015-01-08 12:03 GMT+01:00 Nadav Har'El <nyh@cloudius-systems.com>:

> On Tue, Jan 6, 2015 at 11:59 AM, Nadav Har'El <nyh@cloudius-systems.com>
> wrote:
>
>> Pawel, perhaps this is related to commit
>> 28bef7c6a44d8061cb7a4b408c8121d5d6b982fe?
>>
>> I wonder if this can be reproduced without Capstan (so far I couldn't).
>>
>
> I found an easy way to reproduce this problem:
>
>     make image=java
>     scripts/run.py -e 'java.so -version'
>
> This is supposed to show Java's version and exit, but it never exits, and
> apparently uses some CPU (13%), I have no idea for what.
>

I don't think that this is the same issue. With 'java.so -version' OSv just
waits indefinitely for a detached threads to exits, what never happens.
Rowland, however, encountered an abort somewhere in application destructor,
which looks like a different problem.

**Comment by nyh** [comment]
On Tue, Jan 6, 2015 at 11:47 AM, Rowland Watkins <notifications@github.com>
wrote:

> Hi Dor,
>
> Ah, ok, added -v and I have some interesting output:
>
> [[[
> Building blah...
> OSv v0.16-31-g927ea7e
> eth0: 192.168.122.15
> Waiting for connection from host...
> Uploading files...
> Adding /blah.jar...
> target/scala-2.11/blah-assembly-1.3.jar --> /blah.jar
> Aborted
>
> [backtrace]
> 0x0000000000445371
> 0x00000000004453da
> 0x000000000032ef43
> 0x0000000000392379
> 0x0000000000391266 <???+3740262>
> 0x0000000000413a49 >, boost::signals2::slot >,
> boost::signals2::mutex>::~connection_body()+153>
> 0x000000000021678d boost::detail::sp_counted_base::release()+45
> 0x0000000000414513 >, boost::signals2::slot >, boost::signals2::mutex> >,
> std::allocator >, boost::signals2::slot >, boost::signals2::mutex> > >
> >::_M_clear()+51>
> 0x00000000004145e6 , boost::shared_ptr >, boost::signals2::slot >,
> boost::signals2::mutex> > > >::dispose()+38>
> 0x000000000021678d boost::detail::sp_counted_base::release()+45
> 0x000000000041367d , int, std::less, boost::function, boost::function,
> boost::signals2::mutex>::invocation_state>::dispose()+45>
> 0x000000000021678d boost::detail::sp_counted_base::release()+45
> 0x0000000000413628 , int, std::less, boost::function, boost::function,
> boost::signals2::mutex> >::dispose()+40>
> 0x000000000021678d boost::detail::sp_counted_base::release()+45
> 0x00000000004119f0 osv::application::~application()+128
> 0x00000000002173b3 std::vector<std::shared_ptr<osv::application,
> std::allocatorstd::shared_ptr<osv::application > >::~vector()+131>
> 0x0000000000212ab3
> 0x0000000000440895 <???+4458645>
> 0x00000000003eda07
> 0x00000000003921e5 <???+3744229>
> ]]]
>
> Looks like something is barfing, which is causing the hang - is there any
> other information I can provide you?
>

Hi Pekka, I've been able to reproduce this error without Capstan, and it
seems to me that this std::vector<std::shared_ptr<osv::application<..>>>
which is being destroyed is loader.cc. This vector is also used if we have
a "detached application" started with "&!". The only user of this feature I
know of is httpserver, so I wanted to ask - *does Capstan's base image have
httpserver?*

Anyway, I'm now debugging *why* this problem is happening.


-- 
Nadav Har'El
nyh@cloudius-systems.com

**Comment by tzach** [comment]
> does Capstan's base image have httpserver?

Only if you explicitly include it in the build
All the base image we formally release do have httpserver, as you can see here
https://github.com/cloudius-systems/osv/blob/master/scripts/build-capstan-images

**Comment by nyh** [comment]
On Sun, Jan 11, 2015 at 9:03 PM, Tzach Livyatan <notifications@github.com>
wrote:

> does Capstan's base image have httpserver?
>
> Only if you explicitly include it in the build
> All the base image we formally release do have httpserver, as you can see
> here
>
> https://github.com/cloudius-systems/osv/blob/master/scripts/build-capstan-images
>

Does this mean that when Capstan runs cpiod.so, that httpserver runs in the
background?

(sorry for asking stupid questions, I never looked at these details of
Capstan).


-- 
Nadav Har'El
nyh@cloudius-systems.com

**Comment by nyh** [comment]
On Mon, Jan 12, 2015 at 12:26 AM, Nadav Har'El <nyh@cloudius-systems.com>
wrote:

>
> On Sun, Jan 11, 2015 at 9:03 PM, Tzach Livyatan <notifications@github.com>
> wrote:
>
>> does Capstan's base image have httpserver?
>>
>> Only if you explicitly include it in the build
>> All the base image we formally release do have httpserver, as you can see
>> here
>>
>> https://github.com/cloudius-systems/osv/blob/master/scripts/build-capstan-images
>>
>
> Does this mean that when Capstan runs cpiod.so, that httpserver runs in
> the background?
>

Answering my own question, I think it is "yes" - whenever httpserver is in
the image, we tried very hard to make sure it always runs - even if the
user tries to specify a different command line. So it is likely that when
Capstan runs a base image which includes httpserver, httpserver does run.

Capstan can avoid running httpserver by using the "--init" kernel option
when running cpio.d.
My patch on the mailing list earlier should fix the httpserver shutdown
crash, but Capstan should probably avoid running it in the first place?



-- 
Nadav Har'El
nyh@cloudius-systems.com

**Comment by rowlandwatkins** [comment]
I think we can close this - I'm using the fedora openjdk8, and haven't had any problems since.
