### ISSUE TITLE
Capstan CPIO fails on parallel builds

### ISSUE THREAD

**Issue by rowlandwatkins** [cloudius-systems/capstan#139]
Hi folks,

Interesting error (I think) found when executing lots of capstan builds on Jenkins:

1) build-a runs, hdd runs out of space, uploading artifacts using CPIO hangs, build never completes
2) (space recovered) build-b runs, uploads between 25-75% of artifacts (4 files), then crashes with exit code 1
3) manual "capstan build" in build directory fails

Killing build-a run, releases something in capstan that allows CPIO to complete.

Only noticed this error when I saw a borked build run and "Waiting for connection from host" in the VM when running.

Is there some magic locking going on that affects parallel builds?

Cheers,

Rowland

**Comment by dorlaor** [comment]
On Fri, Mar 13, 2015 at 9:26 AM, Rowland Watkins <notifications@github.com>
wrote:

> Hi folks,
>
> Interesting error (I think) found when executing lots of capstan builds on
> Jenkins:
>
> 1) build-a runs, hdd runs out of space, uploading artifacts using CPIO
> hangs, build never completes
> 2) (space recovered) build-b runs, uploads between 25-75% of artifacts (4
> files), then crashes with exit code 1
> 3) manual "capstan build" in build directory fails
>
> Killing build-a run, releases something in capstan that allows CPIO to
> complete.
>
> Only noticed this error when I saw a borked build run and "Waiting for
> connection from host" in the VM when running.
>
> Is there some magic locking going on that affects parallel builds?
>
The only common thing between build is the usage of qemu to initialize the
new
ZFS partition. Potentially there are common ports that may be used and the
cpio
streaming from the host to the guest gets multiplexed wrong.

**Comment by rowlandwatkins** [comment]
@dorlaor Many thanks for the clarification - I think I can just make sure that capstan fails the build in such cases and see how it goes.
