### ISSUE TITLE
Local Capstan repository

### ISSUE THREAD

**Issue by rowlandwatkins** [cloudius-systems/capstan#140]
Hi folks,

In the Capstan blurb on the OSv website it mentions that I can create my own capstan repository on AWS or even git.

My use case is pretty simple - I'd like to create a pipline in Jenkins that takes an authoritative image then uses that to deploy to a different hypervisor:
1) job to create image (baseline)
2) job to deploy to AWS, GCE, ESXi

At present I need to create n images for each hypervisor, which makes chasing configuration changes a little challenging.

Any hints/procedures on how to go about this?

Cheers,

Rowland

**Comment by dorlaor** [comment]
On Thu, Mar 19, 2015 at 12:02 PM, Rowland Watkins <notifications@github.com>
wrote:

> Hi folks,
>
> In the Capstan blurb on the OSv website it mentions that I can create my
> own capstan repository on AWS or even git.
>
> My use case is pretty simple - I'd like to create a pipline in Jenkins
> that takes an authoritative image then uses that to deploy to a different
> hypervisor:
> 1) job to create image (baseline)
> 2) job to deploy to AWS, GCE, ESXi
>
> At present I need to create n images for each hypervisor, which makes
> chasing configuration changes a little challenging.
>
> Any hints/procedures on how to go about this?
>

Tzach and Pekka are the experts, however, it should be simple:
Just git grep the capstan code for 's3' - there is a URL to download
from. You should just parametricize it.
For upload, there is a script under the osv project
named: scripts/upload-capstan-release

**Comment by penberg** [comment]
@rowlandwatkins There's a "-u" command line option available for various Capstan commands now. You can use that to point Capstan to your own repository. There's unfortunately no remote repository creation support in Capstan but if you look at the OSv release scripts, it shouldn't be too difficult to build your own.

**Comment by penberg** [comment]
For future reference: the functionality was introduced in commit 9ede8ae36ad351dd3ac1e9e0d860ca4811bcc643.
