### ISSUE TITLE
Add Golang Example

### ISSUE THREAD

**Issue by pyros2097** [cloudius-systems/capstan#142]
Is there anyway you can run a compiled go app in osv?

**Comment by dorlaor** [comment]
On Thu, Apr 16, 2015 at 1:09 PM, pyros2097 <notifications@github.com> wrote:

> Is there anyway you can run a compiled go app in osv?
>

It's in the making - check this thread:
https://groups.google.com/forum/#!topic/osv-dev/eIyzdvzXwfY
